#ifndef COMMON_H
#define COMMON_H
#include <QDebug>
#include "version.h"

#define SW_NAME     "AcquaThermoNet"

/* Version, git commit and build time: version.h, generated by version.pri */
#define SW_VER      ATN_VERSION
#define SW_BANNER   SW_NAME " v" SW_VER " (git " ATN_GIT_COMMIT ", built " ATN_BUILD_TIMESTAMP ")"


/********************************************************
 *
 *******************************************************/
/*
#if DEVICE == DISPLAY32
#pragma message "Device DISPLAY32"
#elif DEVICE == DISPLAY64
#pragma message "Device DISPLAY64"
#elif DEVICE == DESKTOP
#pragma message "Device DESKTOP"
#else
#error "Device not matched"
#endif
*/

/* Exit codes read by the package start.sh: 0 = stopped on purpose (no
 * restart), EXIT_ALREADY_RUNNING = another instance owns the target (no
 * restart), anything else or a signal = crash (restarted) */
#define EXIT_ALREADY_RUNNING    3

/* Relays on the Modbus board, numbered 1..RELAY_NUM_MAX */
#define RELAY_NUM_MAX   8

/* Common to some files */
typedef struct {
    quint16 port = 1883;
    QString address;
    QString uname;
    QString password;
    /* TLS */
    bool    tls = false;
    bool    tlsVerify = true;       /* verify the broker certificate and name */
    QString caFile;                 /* PEM, empty: system CAs */
    QString certFile;               /* PEM client certificate, optional */
    QString keyFile;                /* PEM client key, with certFile */
    QString peerName;               /* name in the broker certificate, empty: broker_addr */
} mqtt_brk_t;


typedef struct {
    QString comune;
    double  temp    = 0;        /* °C, not rounded: frost protection threshold */
    int     hum     = 0;        /* % */
    double  ws      = 0;        /* wind m/s */
    double  rain    = 0;        /* mm */
    int     press   = 0;        /* hPa */
    QString hour;
    QString utcdel;
} weather_t;

#endif // COMMON_H
